---
title: "Education Level Vs Social Media Usage"
author: "Kushal Kundanmal"
date: "2020-09-19"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---



<div id="general-social-survey-gss" class="section level1">
<h1>General Social Survey (GSS)</h1>
<p>In this analysis, we will be taking a look how social media (Twitter, Instagram, Snapchat and Email) usage differs by education levels. The data we use, comes from a 2016 General Social Survey.</p>
<pre class="r"><code>gss &lt;- read_csv(here::here(&quot;data&quot;, &quot;smallgss2016.csv&quot;), 
                na = c(&quot;&quot;, &quot;Don&#39;t know&quot;,
                       &quot;No answer&quot;, &quot;Not applicable&quot;))</code></pre>
<div id="instagram-and-snapchat-by-sex" class="section level2">
<h2>Instagram and Snapchat, by sex</h2>
<p>We have calculated the 95% confidence interval for the proportion of Snapchat and Instagram users in 2016.</p>
<pre class="r"><code>gss_snap_insta &lt;- gss %&gt;%
  filter(snapchat %in% c(&quot;Yes&quot;,&quot;No&quot;,&quot;NA&quot;),
         instagrm %in% c(&quot;Yes&quot;,&quot;No&quot;,&quot;NA&quot;)) %&gt;%
  mutate(snap_insta=case_when(
    snapchat==&quot;Yes&quot; | instagrm==&quot;Yes&quot; ~ &quot;Yes&quot;,
    snapchat==&quot;NA&quot; &amp; instagrm==&quot;NA&quot; ~ &quot;NA&quot;,
    TRUE ~ &quot;No&quot;)) %&gt;% 
  filter(snap_insta!=&quot;NA&quot;) %&gt;% 
  specify(response=snap_insta,success=&quot;Yes&quot;) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;%
  calculate(stat=&quot;prop&quot;)
snap_insta_ci &lt;- gss_snap_insta %&gt;%  get_confidence_interval(level = 0.95,type=&quot;percentile&quot;)
gss_snap_insta %&gt;% visualize(bins = 15) + 
  shade_confidence_interval(endpoints = snap_insta_ci)</code></pre>
<p><img src="/projects/project3/index_files/figure-html/snap_insta-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>snap_insta_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.349    0.402</code></pre>
</div>
<div id="twitter-by-education-level" class="section level2">
<h2>Twitter, by education level</h2>
<p>We have calculated the 95% confidence intervals for the proportion of Twitter users who have a bachelors degree or higher in 2016.</p>
<div id="sample-proportion-of-bachelor_graduates-that-use-twitter" class="section level3">
<h3>Sample Proportion of bachelor_graduate’s that use Twitter:</h3>
<pre class="r"><code># turn degree to a factor
twitter_gss &lt;- gss %&gt;% 
  mutate(degree=factor(degree,
                       levels = c(
                         &quot;Lt high school&quot;,
                         &quot;High School&quot;,
                         &quot;Junior college&quot;,
                         &quot;Bachelor&quot;,
                         &quot;Graduate&quot;),
                       ordered=TRUE))
# create bachelor_graduate var
twitter_gss &lt;- gss %&gt;% 
  mutate(bachelor_graduate=case_when(
    degree==&quot;Bachelor&quot; |degree==&quot;Graduate&quot; ~ &quot;Yes&quot;,
    is.na(degree) ~ &quot;NA&quot;,
    TRUE ~ &quot;No&quot;
  ))
#get sample proportions
twitter_gss_prop &lt;- twitter_gss %&gt;%
  filter(bachelor_graduate==&quot;Yes&quot;,twitter %in% c(&quot;Yes&quot;,&quot;No&quot;)) %&gt;% 
  summarise(twit_yes=mean(twitter==&quot;Yes&quot;),
            twit_no=mean(twitter==&quot;No&quot;))
twitter_gss_prop</code></pre>
<pre><code>## # A tibble: 1 x 2
##   twit_yes twit_no
##      &lt;dbl&gt;   &lt;dbl&gt;
## 1    0.233   0.767</code></pre>
<p>###The 95% Confidence Levels for respondents that are bachelor_graduate that use twitter:</p>
<pre class="r"><code>twitter_gss_yes &lt;- twitter_gss %&gt;% 
  filter(bachelor_graduate==&quot;Yes&quot;,twitter %in% c(&quot;Yes&quot;,&quot;No&quot;)) %&gt;%
  specify(response=twitter,success=&quot;Yes&quot;) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;%
  calculate(stat=&quot;prop&quot;)
#get CI for yes
twitter_gss_yes_ci &lt;- twitter_gss_yes %&gt;%
  get_confidence_interval(level = 0.95,type=&quot;percentile&quot;)
#visualize
twitter_gss_yes %&gt;% visualize(bins = 15) + 
  shade_confidence_interval(endpoints = twitter_gss_yes_ci)</code></pre>
<p><img src="/projects/project3/index_files/figure-html/twitter_yes-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>twitter_gss_yes_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.196    0.274</code></pre>
</div>
<div id="the-95-confidence-levels-for-respondents-that-are-bachelors-or-above-that-do-not-use-twitter" class="section level3">
<h3>The 95% Confidence Levels for respondents that are Bachelors or above that Do Not use twitter</h3>
<pre class="r"><code>twitter_gss_no &lt;- twitter_gss %&gt;% 
  filter(bachelor_graduate==&quot;Yes&quot;,twitter %in% c(&quot;Yes&quot;,&quot;No&quot;)) %&gt;%
  specify(response=twitter,success=&quot;No&quot;) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;%
  calculate(stat=&quot;prop&quot;)

#get CI for no
twitter_gss_no_ci &lt;- twitter_gss_no %&gt;%
  get_confidence_interval(level = 0.95,type=&quot;percentile&quot;)
#visualize
twitter_gss_no %&gt;% visualize(bins = 15) + 
  shade_confidence_interval(endpoints = twitter_gss_no_ci)</code></pre>
<p><img src="/projects/project3/index_files/figure-html/twitter_no-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>twitter_gss_no_ci</code></pre>
<pre><code>## # A tibble: 1 x 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1    0.730    0.804</code></pre>
<p>We can see that in respondents who have an education level of ‘Bachelors’ or higher, that the CI for the proportion that USE Twitter, overlaps with the CI for the proportion that DO NOT USE Twitter.</p>
<p>The CI for the proportion of Non Twitter Users is between 73% and 80%,
whereas the CI for the proportion of Twitter Users is between 20% and 27%.
Towards the higher ranges of both of the proportion CI’s, the intervals would overlap.</p>
</div>
</div>
<div id="email-usage" class="section level2">
<h2>Email usage</h2>
<p>Can we estimate the <em>population</em> parameter on time spent on email weekly?</p>
<pre class="r"><code>email_gss &lt;- gss %&gt;% 
  mutate(emailhr=as.numeric(emailhr),emailmin=as.numeric(emailmin))

email_gss &lt;- email_gss %&gt;%
  mutate(emailmin_total=emailhr*60+emailmin)
skim(email_gss %&gt;% select(emailmin_total))</code></pre>
<table>
<caption>(#tab:email_usage_skim)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">email_gss %&gt;% select(emai…</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">2867</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">1</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">numeric</td>
<td align="left">1</td>
</tr>
<tr class="odd">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">emailmin_total</td>
<td align="right">1218</td>
<td align="right">0.58</td>
<td align="right">417</td>
<td align="right">680</td>
<td align="right">0</td>
<td align="right">50</td>
<td align="right">120</td>
<td align="right">480</td>
<td align="right">6000</td>
<td align="left">▇▁▁▁▁</td>
</tr>
</tbody>
</table>
<p>The median is 120, the mean is 417.</p>
<p>It appears that median is a better measure, as there are outliers and a skewed tail to the higher values that are effecting the mean. The median is less affected by outliers and better represents the central tendency of the variable.</p>
<pre class="r"><code>email_gss &lt;- email_gss %&gt;% 
  specify(response=emailmin_total) %&gt;% 
  generate(reps=1000,type=&quot;bootstrap&quot;) %&gt;%
  calculate(stat=&quot;mean&quot;)

email_gss_ci &lt;- email_gss %&gt;%
  get_confidence_interval(level = 0.95,type=&quot;percentile&quot;) %&gt;% 
  mutate(lower_ci_hrs=lower_ci%/%60,lower_ci_mins=lower_ci%%60,
         upper_ci_hrs=upper_ci%/%60,upper_ci_mins=upper_ci%%60) 

# Output the confidence interval
email_gss_ci</code></pre>
<pre><code>## # A tibble: 1 x 6
##   lower_ci upper_ci lower_ci_hrs lower_ci_mins upper_ci_hrs upper_ci_mins
##      &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt;         &lt;dbl&gt;        &lt;dbl&gt;         &lt;dbl&gt;
## 1     384.     451.            6          24.2            7          31.0</code></pre>
<p>The confidence interval for the mean email usage in the population is between 6hrs 24min and 7hrs 28min. This seems like a reasonable interval given that the sample mean is 6hrs and 57min.</p>
<p>If we were to increase the confidence level of the interval to 99%, then the range of the interval would increase. This is because, in order to be more confident in the range, you need to cast a wider net to ensure that any possible values are covered by the interval. In general, the greater the confidence level, the greater the range between the high and low points in a confidence interval.</p>
</div>
</div>
